plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rspec_rails
AllCops:
  NewCops: disable
  TargetRubyVersion: 3.4
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{bundle,rails,rake,importmap,setup,brakeman,rubocop}'
    - 'lib/tasks/*.rake'
