# Ansible managed: /Users/tom/Projects/Eventide/wicked_software/deploy/ansible/roles/postgresql/templates/database.yml.j2 modified on 2016-02-03 17:24:02 by tom on Toms-MacBook-Pro.local

default: &default
  adapter: postgresql
  host: localhost
  pool: 5

development:
  <<: *default
  database: wicked_software

  username: wicked_software
  password: feeblelarf12_

test:
  <<: *default
  database: wicked_software_test
