name: check
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      - name: Install dependencies
        run: |
          bundle install

      - name: Run linters
        run: |
          bundle exec rubocop

      - name: Run security checks
        run: |
          bundle exec bundler-audit --update
          bundle exec rubocop
          bundle exec brakeman --quiet
          ./bin/importmap audit

